package com.se325a3.smdb.dao;

import java.util.List;

import com.se325a3.smdb.model.Person;
import com.se325a3.smdb.model.Role;

public interface PersonSmdbDao {
	
	/**
	 * Retrieve a Person from the PERSON table given their id (Primary key)
	 * 
	 * @param id
	 *            The id of the person to retrieve
	 * @return The Person with the id specified
	 */
	Person getPersonById(int id);

	/**
	 * Retrieve an actor (that is, a Person with an entry in the ROLE table)
	 * given their id (Primary key)
	 * 
	 * @param id
	 *            The id of the actor to retrieve
	 * @return The actor with the id specified
	 */
	Person getActorById(int id);

	/**
	 * Retrieve actors (that is, Persons with entries in the ROLE table) given
	 * their first names/the start of their first names
	 * 
	 * @param name
	 *            String to match the first name of the actor against
	 * @return A list of the actors with matching first names to the name
	 *         parameter
	 */
	List<Person> getActorsByFirstName(String name);

	/**
	 * Retrieve actors (that is, Persons with entries in the ROLE table) given
	 * their first names/the start of their last names
	 * 
	 * @param name
	 *            String to match the last name of the actor against
	 * @return A list of the actors with matching last names to the name
	 *         parameter
	 */
	List<Person> getActorsByLastName(String name);

	/**
	 * Retrieve actors (that is, Persons with entries in the ROLE table) given
	 * their first and last names/the start of their first and last names
	 * 
	 * @param firstname
	 *            String to match the first name of the actor against
	 * @param lastname
	 *            String to match the last name of the actor against
	 * @return A list of the actors with matching first and last names to the
	 *         name parameters
	 */
	List<Person> getActorsByFirstNameAndLastName(String firstname,
			String lastname);

	/**
	 * Retrieve actors (that is, Persons with entries in the ROLE table) given
	 * their first or last names/the start of their first and last names
	 * 
	 * @param firstname
	 *            String to match the first name of the actor against
	 * @param lastname
	 *            String to match the last name of the actor against
	 * @return A list of the actors with matching first or last names to the
	 *         name parameters
	 */
	List<Person> getActorsByFirstNameOrLastName(String firstname,
			String lastname);

	/**
	 * Retrieve actors (that is, Persons with entries in the ROLE table) given
	 * the title of the movies they have appeared in
	 * 
	 * @param title
	 *            String with to match the first name of the actor against
	 * @return A list of the actors with matching entries in the ROLE table to a
	 *         Movie with a title starting with the title parameter
	 */
	List<Person> getActorsByMovieTitle(String title);

	/**
	 * Retrieve actors (that is, Persons with entries in the ROLE table) given
	 * the title and production year (primary key) of a specific Movie if they
	 * have appeared in it
	 * 
	 * @param title
	 *            The title of the Movie
	 * @param year
	 *            The production year of the Movie
	 * @return A list of the actors with matching entries in the ROLE table to
	 *         the specified Movie
	 */
	List<Person> getActorsByMovieTitleAndYear(String title, String year);

	/**
	 * Insert a Person into the database
	 * 
	 * @param person
	 *            Person object to be saved in database
	 * @return The id automatically generated by the database for the entry
	 */
	int insertPerson(Person person);
	
}
